<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="privacymodel" nsURI="http://privacymodel/1.0" nsPrefix="privacymodel">
  <eClassifiers xsi:type="ecore:EClass" name="NamedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PrivacyPolicy" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="policyStatements" upperBound="-1"
        eType="#//PolicyStatement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PolicyStatement" eSuperTypes="#//NamedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Data" eSuperTypes="#//NamedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Service" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Subservices" upperBound="-1"
        eType="#//Service"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Provider" eSuperTypes="#//NamedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Region" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="subRegion" upperBound="-1"
        eType="#//Region"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Principal" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Subprincipals" upperBound="-1"
        eType="#//Principal"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="PrivacyStatementType"/>
  <eClassifiers xsi:type="ecore:EEnum" name="DataType"/>
  <eClassifiers xsi:type="ecore:EClass" name="Location" eSuperTypes="#//NamedElement"/>
  <eClassifiers xsi:type="ecore:EEnum" name="ConditionType"/>
  <eClassifiers xsi:type="ecore:EClass" name="Condition"/>
  <eClassifiers xsi:type="ecore:EClass" name="TimeInterval">
    <eStructuralFeatures xsi:type="ecore:EReference" name="intervals" upperBound="2"
        eType="#//TimeStatement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TimeStatement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="DateTime" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Proposal" eType="#//TimeProposal"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TimeProposal">
    <eLiterals name="from"/>
    <eLiterals name="to" value="1"/>
    <eLiterals name="at" value="2"/>
    <eLiterals name="until" value="3"/>
  </eClassifiers>
</ecore:EPackage>
